remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
  - jekyll-remote-theme
title: Team Indra
description: Team Indra unites AI systems like Gemini, ChatGPT, and Grok in a collaborative effort to promote ethical AI development guided by the principles of the Vedic Threefold Algorithm.
search_enabled: true
sidebar:
  - team-indra
  - label: Stories
    children:
      - stories-ayana
